#!/bin/bash

rm -rf .vscode # clear away junk

CFLAGS="\
-fcolor-diagnostics \
-fno-caret-diagnostics \
-Wno-c++11-extensions -Wno-c++11-compat-deprecated-writable-strings \
-Wno-missing-declarations -Wno-empty-body"

CLANG_FILTER="grep -v 'In file included'"

clang++ -std=c++98 -c src/*.cc -I include -I src/cext \
	-g3 -fcolor-diagnostics -ferror-limit=100 \
	$CFLAGS 2>&1 $(RESULT=$?) \
	| grep -v 'In file included'

echo $RESULT
if [[ ! -z $RESULT ]]
then
	rm *.o
	exit
fi

clang++ *.o -o mcatc -g3 | grep -v 'In file included'
rm *.o
